import styles from "./index.module.css";
import Head from "next/head";
import Link from "next/link";
import ItemCard from "~/components/itemCard";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <ItemCard></ItemCard>
      </main>
    </>
  );
}
